namespace CSharpFar.App.Viewer;

/// <summary>Built-in help text lines shown by the F1 help viewer.</summary>
public static class HelpContent
{
    public static readonly string[] Lines =
    [
        "CSharpFar — Console Dual-Panel File Manager",
        new string('═', 60),
        "",
        "PANEL NAVIGATION",
        "  ↑ ↓               Move cursor",
        "  PgUp / PgDn       Move by page",
        "  Home              First item (or start of command line)",
        "  End               Last item  (or end of command line)",
        "  Tab               Switch active panel",
        "  Enter             Enter directory / execute command",
        "  Backspace         Go to parent directory (or delete in command line)",
        "",
        "FILE OPERATIONS",
        "  F3                View file (text viewer)",
        "  F4                Edit file (text editor)",
        "  F5                Copy selected files",
        "  F6                Move / Rename selected files",
        "  F7                Create folder",
        "  F8                Delete selected files (with confirmation)",
        "  F2                User menu  (edit user-menu.json to customise)",
        "",
        "SELECTION",
        "  Insert            Toggle selection on current item",
        "  Ctrl+A            Select all / Deselect all",
        "  Ctrl+*            Invert selection",
        "",
        "SORTING  (active panel)",
        "  Ctrl+F3           Sort by name",
        "  Ctrl+F4           Sort by extension",
        "  Ctrl+F5           Sort by last-write date",
        "  Ctrl+F6           Sort by size",
        "  (Press the same key again to reverse sort order)",
        "",
        "HISTORY",
        "  Alt+F8            Command history",
        "  Alt+F11           File history",
        "  Alt+F12           Directory history",
        "",
        "SEARCH",
        "  Alt+F7            Search files by mask (e.g. *.cs)",
        "",
        "VIEW MODES",
        "  Ctrl+O            Toggle panels on/off — shows shell output underneath",
        "  Ctrl+Q            Quick view — preview file in the inactive panel",
        "  Alt+1             Full view mode for active panel",
        "  Alt+2             Brief two-column view mode for active panel",
        "  Ctrl+S / F9       Settings: panel view modes and palette",
        "",
        "IN VIEWER  (F3)",
        "  ↑ ↓               Scroll lines",
        "  PgUp / PgDn       Scroll by page",
        "  ← →               Scroll horizontally",
        "  Home              First line / left edge",
        "  End               Last line",
        "  F10 / Esc         Close viewer",
        "",
        "IN EDITOR  (F4)",
        "  F2                Save file",
        "  Ctrl+Home         Go to start of file",
        "  Ctrl+End          Go to end of file",
        "  F10 / Esc         Close (prompts to save if there are unsaved changes)",
        "",
        "GENERAL",
        "  F1                This help",
        "  F10               Quit CSharpFar",
        "",
        "CONFIGURATION",
        "  Settings:   %APPDATA%\\CSharpFar\\settings.json",
        "  User menu:  %APPDATA%\\CSharpFar\\user-menu.json",
        "  History:    %APPDATA%\\CSharpFar\\history.json",
        "",
        "  Portable mode: create a file named CSharpFar.portable next to the .exe",
        "  All config files will go to CSharpFar.config\\ beside the executable.",
    ];

    public static int MaxLineLength { get; } = Lines.Max(l => l.Length);
}
