namespace CSharpFar.App.Editor;

public static class EditorKeyboardCommandInventory
{
    public static IReadOnlyList<EditorKeyCommandBinding> Commands { get; } =
    [
        new("copy-selection", ConsoleKey.C, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Copy selection"),
        new("copy-selection", ConsoleKey.Insert, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Copy selection"),
        new("cut-selection", ConsoleKey.X, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Cut selection"),
        new("cut-selection", ConsoleKey.Delete, ConsoleModifiers.Shift, EditorKeyCommandStatus.Implemented, "Cut selection"),
        new("paste", ConsoleKey.V, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Paste clipboard text"),
        new("paste", ConsoleKey.Insert, ConsoleModifiers.Shift, EditorKeyCommandStatus.Implemented, "Paste clipboard text"),
        new("delete-block-or-line", ConsoleKey.F8, 0, EditorKeyCommandStatus.Implemented, "Delete selection or current line"),
        new("delete-to-line-end", ConsoleKey.K, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Delete to line end"),
        new("delete-to-line-end", ConsoleKey.D, ConsoleModifiers.Alt, EditorKeyCommandStatus.Implemented, "Delete to line end"),
        new("toggle-syntax-highlighting", ConsoleKey.H, ConsoleModifiers.Alt, EditorKeyCommandStatus.Implemented, "Toggle syntax highlighting for current editor session"),
        new("select-syntax-language", ConsoleKey.L, ConsoleModifiers.Alt, EditorKeyCommandStatus.Implemented, "Select syntax language for current editor session"),
        new("select-syntax-theme", ConsoleKey.T, ConsoleModifiers.Alt, EditorKeyCommandStatus.Implemented, "Select syntax theme for current editor session"),
        new("delete-word-left", ConsoleKey.Backspace, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Delete previous word"),
        new("delete-word-right", ConsoleKey.Delete, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Delete next word"),
        new("delete-word-right", ConsoleKey.T, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Delete next word"),
        new("delete-block", ConsoleKey.D, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Delete selected block"),
        new("copy-block", ConsoleKey.P, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Copy selected block to cursor"),
        new("move-block", ConsoleKey.M, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Move selected block to cursor"),
        new("clear-selection", ConsoleKey.U, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Clear selection"),
        new("shift-block-left", ConsoleKey.U, ConsoleModifiers.Alt, EditorKeyCommandStatus.Implemented, "Shift block or current line left"),
        new("shift-block-right", ConsoleKey.I, ConsoleModifiers.Alt, EditorKeyCommandStatus.Implemented, "Shift block or current line right"),
        new("delete-line", ConsoleKey.Y, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Delete current line"),
        new("redo", ConsoleKey.Z, ConsoleModifiers.Control | ConsoleModifiers.Shift, EditorKeyCommandStatus.Implemented, "Redo"),
        new("set-numbered-bookmark", ConsoleKey.D0, ConsoleModifiers.Control | ConsoleModifiers.Shift, EditorKeyCommandStatus.Implemented, "Set numbered bookmark 0"),
        new("set-numbered-bookmark", ConsoleKey.D1, ConsoleModifiers.Control | ConsoleModifiers.Shift, EditorKeyCommandStatus.Implemented, "Set numbered bookmark 1"),
        new("set-numbered-bookmark", ConsoleKey.D2, ConsoleModifiers.Control | ConsoleModifiers.Shift, EditorKeyCommandStatus.Implemented, "Set numbered bookmark 2"),
        new("set-numbered-bookmark", ConsoleKey.D3, ConsoleModifiers.Control | ConsoleModifiers.Shift, EditorKeyCommandStatus.Implemented, "Set numbered bookmark 3"),
        new("set-numbered-bookmark", ConsoleKey.D4, ConsoleModifiers.Control | ConsoleModifiers.Shift, EditorKeyCommandStatus.Implemented, "Set numbered bookmark 4"),
        new("set-numbered-bookmark", ConsoleKey.D5, ConsoleModifiers.Control | ConsoleModifiers.Shift, EditorKeyCommandStatus.Implemented, "Set numbered bookmark 5"),
        new("set-numbered-bookmark", ConsoleKey.D6, ConsoleModifiers.Control | ConsoleModifiers.Shift, EditorKeyCommandStatus.Implemented, "Set numbered bookmark 6"),
        new("set-numbered-bookmark", ConsoleKey.D7, ConsoleModifiers.Control | ConsoleModifiers.Shift, EditorKeyCommandStatus.Implemented, "Set numbered bookmark 7"),
        new("set-numbered-bookmark", ConsoleKey.D8, ConsoleModifiers.Control | ConsoleModifiers.Shift, EditorKeyCommandStatus.Implemented, "Set numbered bookmark 8"),
        new("set-numbered-bookmark", ConsoleKey.D9, ConsoleModifiers.Control | ConsoleModifiers.Shift, EditorKeyCommandStatus.Implemented, "Set numbered bookmark 9"),
        new("go-numbered-bookmark", ConsoleKey.D0, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Go to numbered bookmark 0"),
        new("go-numbered-bookmark", ConsoleKey.D1, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Go to numbered bookmark 1"),
        new("go-numbered-bookmark", ConsoleKey.D2, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Go to numbered bookmark 2"),
        new("go-numbered-bookmark", ConsoleKey.D3, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Go to numbered bookmark 3"),
        new("go-numbered-bookmark", ConsoleKey.D4, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Go to numbered bookmark 4"),
        new("go-numbered-bookmark", ConsoleKey.D5, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Go to numbered bookmark 5"),
        new("go-numbered-bookmark", ConsoleKey.D6, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Go to numbered bookmark 6"),
        new("go-numbered-bookmark", ConsoleKey.D7, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Go to numbered bookmark 7"),
        new("go-numbered-bookmark", ConsoleKey.D8, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Go to numbered bookmark 8"),
        new("go-numbered-bookmark", ConsoleKey.D9, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Go to numbered bookmark 9"),
        new("insert-active-panel-file-name", ConsoleKey.Enter, ConsoleModifiers.Shift, EditorKeyCommandStatus.Implemented, "Insert active panel file name"),
        new("insert-passive-panel-file-name", ConsoleKey.Enter, ConsoleModifiers.Control | ConsoleModifiers.Shift, EditorKeyCommandStatus.Implemented, "Insert passive panel file name"),
        new("insert-edited-file-path", ConsoleKey.F, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Insert edited file path"),
        new("scroll-up", ConsoleKey.UpArrow, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Scroll viewport up"),
        new("scroll-down", ConsoleKey.DownArrow, ConsoleModifiers.Control, EditorKeyCommandStatus.Implemented, "Scroll viewport down"),
        new("macros", ConsoleKey.F11, 0, EditorKeyCommandStatus.OutOfScope, "Plugin and macro commands are outside the editor command slice"),
    ];
}
