namespace CSharpFar.App.Commands;

internal static class DefaultApplicationCommands
{
    public static IReadOnlyList<IApplicationCommand> Create() =>
    [
        new HelpCommand(),
        new UserMenuCommand(),
        new ViewFileCommand(),
        new EditFileCommand(),
        new OpenCreateFileCommand(),
        new CopyCommand(),
        new MoveCommand(),
        new RenameCommand(),
        new CreateFolderCommand(),
        new DeleteCommand(),
        new OpenFileAttributesCommand(),
        new OpenTopMenuCommand(),
        new QuitCommand(),
        new SelectLeftDriveCommand(),
        new SelectRightDriveCommand(),
        new SearchFilesCommand(),
        new CompareCommand(CompareCommandKind.Folders),
        new CompareCommand(CompareCommandKind.FileSets),
        new CommandHistoryCommand(),
        new FileHistoryCommand(),
        new DirectoryHistoryCommand(),
        new TogglePanelsCommand(),
        new SwapPanelsCommand(),
        new SortByNameCommand(),
        new SortByExtensionCommand(),
        new SortByLastWriteTimeCommand(),
        new SortBySizeCommand(),
        new OpenCurrentItemCommand(),
        new NavigateToRootCommand(),
        new PanelSetViewModeCommand(),
        new PanelSetSortModeCommand(),
        new PanelToggleReverseSortCommand(),
        new PanelRefreshCommand(),
        new ModuleOpenCommand(),
        new PrintTerminalDiagnosticsCommand(),
        new OpenSettingsCommand(),
        new OpenDirectoryShortcutEditorCommand(),
        new NavigateToDirectoryShortcutCommand(),
        new ToggleShowHiddenAndSystemFilesCommand(),
        new ToggleHighlightFilesCommand(),
        new ToggleSelectFoldersCommand(),
        new ToggleRightClickSelectsFilesCommand(),
        new ToggleSortFoldersByExtensionCommand(),
        new ToggleShowStatusLineCommand(),
        new ToggleShowFilesTotalInformationCommand(),
        new ToggleShowFreeSizeCommand(),
        new ToggleShowSortModeLetterCommand(),
        new ToggleShowParentDirectoryInRootFoldersCommand(),
        new SaveSettingsCommand(),
    ];
}
